# Site settings
title: "Victor Johnson - Data Scientist"
description: "I am a data scientist and AI entusiast. I have 5+ years experience and is currently living in the United kingdom. I am happy to help with data science projects"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Victor Johnson"
resume_title:                   "Data Scientist & AI enthusiast"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "mail.victorjohnson@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+44-7469630359"
resume_contact_address:         "Norwich, Norfolk, United Kingdom"

resume_header_contact_info:     "Norwich, Norfolk, United Kingdom • +44-7469630359 • mail.victorjohnson@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I am a data scientist and AI entusiast. I have 5+ years experience and is currently living in the United kingdom. I am happy to help with data science projects</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/victorjohnsonk"
  resume_twitter_url:           "#"
  resume_dribbble_url:          "#"
  resume_facebook_url:          "#"
  resume_linkedin_url:          "#"
  resume_instagram_url:         "#"
  resume_website_url:           "http://victorjohnson.online"
  resume_medium_url:            "#"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
