# Site settings
title: Victor Johnson - Data Scientist
description: Personal website of Victor Johnson - Data Scientist
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Victor Johnson
user_description: Personal website of Victor Johnson - Data Scientist
user_title: Data Scientist
email: hello@victorjohnson.online
twitter_username: lorem_ipsum
github_username:  lorem_ipsum
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: "G-MEK4W87RJL"

exclude: ['package.json', 'src' , 'node_modules']
